name: backend

on: 
  push: 
    branches: 
      - main
  schedule: 
      - cron: '0 12 * * *'

defaults: 
  run: 
    working-directory: backend

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 16.x

      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build
      
      - run: node dist/index.js &
      - run: npx wait-on -t 10000 http://localhost:8080/api/health
      - run: npm run test:api
      

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: backend/dist/index.js
          retention-days: 5

deploy: 
  needs: build
  if: github.event_name ==  'push'
  runs-on: ubuntu-latest
  steps: 
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BACKEND_SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.BACKEND_SERVER_KNOWN_HOSTS }}

      - run: rsync -v -e dist/index.js ${SERVER_USER@${SERVER_IP}:~/index.js
        env: 
          SERVER_USER: ${{ serects.BACKEND_SERVER_USER }}
          SERVER_IP: ${{ serects.BACKEND_SERVER_IP }}
      - run: ssh ${SERVER_USER@${SERVER_IP} sudo systemctl restart backend
        env: 
          SERVER_USER: ${{ serects.BACKEND_SERVER_USER }}
          SERVER_IP: ${{ serects.BACKEND_SERVER_IP }}
      - run: ssh ${SERVER_USER@${SERVER_IP} systemctl sutatus backend
        env: 
          SERVER_USER: ${{ serects.BACKEND_SERVER_USER }}
          SERVER_IP: ${{ serects.BACKEND_SERVER_IP }}