name: frontend

on: 
  push: 
    branches: 
      - main

defaults: 
  run: 
    working-directory: frontend

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: aws s3 sync . s3://github-actions-s3-nemotos --exact-timestamps --region ap-southeast-2
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_AWS_SECRET_ACCESS_KEY }}