name: frontend

on: 
  push: 
    branches: 
      - main
    paths:
      - 'frontend/**'
      - '.github/**'

defaults: 
  run: 
    working-directory: frontend

permissions:
  id-token: write
  contents: read

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::679513807641:role/github-actions-frontend-deployment-role
          aws-region: ap-southeast-2

      - run: aws s3 sync . s3://github-actions-s3-nemotos --exact-timestamps --region ap-southeast-2